### ISSUE TITLE
Identity-Based Signatures

### ISSUE THREAD

**Issue by bobomate** [battila7/cryptid-java#2]
Hello,

How would I go about implementing identity-based signatures? I noticed that you have added Hess Identity Based Signatures to cryptiid-native. What needs to be done to implement this in the Java version?

Thank you!

**Comment by AVecsi** [comment]
Hi @bobomate!

We are not planning to implement any more protocols in the java version of CryptID, but we would be more than happy if we would receive pull requests.

If you want to implement the Hess signature protocol yourself, just fork the repository and make it happen. :)

As I believe the Hess protocol is highly based on the Boneh-Franklin scheme, so all the required arithmetics are implemented already, all you need to do is to use the right function calls. If you start working based on our Identity-based Encryption implementation and the native Hess implementation, it shouldn't be difficult to get it done.

If you plan to implement it, please add some tests to your code and open a pull request, so I or @battila7 can review it and merge it to CryptID-java if it is correct.
